port:
  8080

db:
  host:
    "192.168.3.129"
  port:
    3306
  database:
    "product"
  username:
    "root"
  password:
    "123456"

logger:
  file_name:
    "./test.log"
  log_level:
    -1
  max_size:
    10
  max_backups:
    5
  max_age:
    30
  compress:
    false